version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    working_directory: ~/majorproject-7-tues-14-30-1/FrontEnd/agme-app
    # Reuse Docker container specification given by the node Orb
    executor: node/default
    steps:
      - checkout:
          path: ~/majorproject-7-tues-14-30-1
      
      - run:
          command: |
            ls
            

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
