version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    working_directory: ~/CCI-FrontEnd
    # Reuse Docker container specification given by the node Orb
    executor: node/default
    steps:
      - checkout
      - run: cd FrontEnd/agme-app
      - run: ls

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
