version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build-front-end:
    working_directory: ~/majorproject-7-tues-14-30-1/FrontEnd/agme-app
    # Reuse Docker container specification given by the node Orb
    executor: node/default
    steps:
      - checkout:
          path: ~/majorproject-7-tues-14-30-1
      # Install the latest npm - the node Orb takes care of it
      - node/install-npm
      # Install dependencies - the node Orb take care of installation and dependency caching
      - node/install-packages:
          app-dir: ~/majorproject-7-tues-14-30-1/FrontEnd/agme-app
          cache-path: node_modules
          override-ci-command: npm i
      # Save workspace for subsequent jobs (i.e. test)
      - persist_to_workspace:
          root: .
          paths:
            - .


  test-front-end:
      docker:
        # The primary container is an instance of the first image listed. The job's commands run in this container.
        - image: cimg/node:current
        # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
        - image: mongo:4.2
      steps:
        # Reuse the workspace from the build job
        - attach_workspace:
            at: .
        - run:
            name: Front end tests
            command: npm test


  test-back-end:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: ./mvnw test


  build-back-end:
    working_directory: ~/majorproject-7-tues-14-30-1/backEnd
    docker:
      - image: circleci/openjdk:stretch
    steps:

      - checkout
      - run: ./mvnw -Dmaven.test.skip=true package
      - persist_to_workspace:
          root: .
          paths:
            - .


workflows:
  version: 2
  build_and_test:
    jobs:
      - build-front-end
      - test-front-end:
          requires:
            - build-front-end
      - build-back-end
      - test-back-end:
          requires:
            - build-back-end
